name: iOS starter workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-15   
    env:
      SCHEME: MIHF 
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16.3
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.3'

      - name: Build
        shell: bash
        run: |
          set -eo pipefail

          if compgen -G "*.xcworkspace" >/dev/null; then
            BUILD_FLAG="-workspace"
            FILE_PATH=$(ls -1d *.xcworkspace | head -n1)
          else
            BUILD_FLAG="-project"
            FILE_PATH=$(ls -1d *.xcodeproj | head -n1)
          fi

          echo "Found Xcode file: $FILE_PATH"

          DEVICE_ID=$(xcrun simctl list devices available |
                      awk '/iPhone/ { gsub(/[()]/,""); print $NF; exit }')

          echo "Using simulator: $DEVICE_ID"

          xcodebuild \
            build-for-testing \
            $BUILD_FLAG "$FILE_PATH" \
            -scheme "$SCHEME" \
            -destination "id=$DEVICE_ID"
