name: iOS starter workflow

on:
  push:        { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  build:
    runs-on: macos-15      # ⬅️ образ с Xcode 16
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 16.3
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.3' 

      - name: Build & test
        run: |
          SCHEME='MIHF'

          DESTINATION=$(xcrun xctrace list devices 2>&1 |
                         awk -F'[()]' '/iPhone/{print $1; exit}' |
                         sed 's/ *$//')

          if compgen -G "*.xcworkspace" >/dev/null; then
            BUILD_FLAG="-workspace"
            FILE_PATH=$(ls -1d *.xcworkspace | head -n1)
          else
            BUILD_FLAG="-project"
            FILE_PATH=$(ls -1d *.xcodeproj | head -n1)
          fi

          xcodebuild \
            build-for-testing \
            -scheme "$SCHEME" \
            "$BUILD_FLAG" "$FILE_PATH" \
            -destination "platform=iOS Simulator,name=$DESTINATION"
