name: iOS starter workflow

on:
  push:        { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  build:
    runs-on: macos-15      # ⬅️ образ с Xcode 16
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 16.3
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.3' 

      - name: Build & test
        run: |
          SCHEME='MIHF'           # <- впишите вашу схему руками
          DESTINATION="$(xcrun xctrace list devices 2>&1 | \
                         awk -F'[()]' '/iPhone/{print $1; exit}' | \
                         sed 's/ *$//')"
          FILE=$(ls *.xcworkspace 2>/dev/null || ls *.xcodeproj)

          xcodebuild \
            build-for-testing \
            -scheme "$SCHEME" \
            -destination "platform=iOS Simulator,name=$DESTINATION" \
            -workspace "$FILE" # или -project, если нет workspace
